var s = new Stack();
    s.push("gerardo");
    s.push("ismael ");
    s.push("garcia");
        console.log("length: " + s.length());
        console.log(s.peek());
var popped = s.pop();
        console.log("The popped element is: " + popped);
        console.log(s.peek());
    s.push("gonzalez");
        console.log(s.peek());
    s.clear();
        console.log("length: " + s.length());
        console.log(s.peek());
    s.push("Clayton");
        console.log(s.peek());
